# Generated by Django 4.1.2 on 2022-10-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bankname", models.CharField(max_length=40)),
                ("address", models.CharField(blank=True, max_length=40, null=True)),
                ("DoE", models.DateTimeField()),
                ("bankID", models.IntegerField()),
                ("url", models.URLField(default="www.rbi.co.in")),
            ],
        ),
        migrations.CreateModel(
            name="bankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=40)),
                ("surname", models.CharField(blank=True, max_length=40, null=True)),
                ("emailid", models.EmailField(max_length=40)),
                ("DOI", models.DateTimeField()),
                ("accnumber", models.IntegerField()),
                ("url", models.URLField(default="www.google.com")),
                (
                    "mybankname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DemoApp.bankdetails",
                    ),
                ),
            ],
        ),
    ]
